version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: dm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dm_project
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: dm_memgraph
    ports:
      - "7687:7687"
      - "3000:3000"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    restart: unless-stopped

volumes:
  pgdata:
  mg_lib:
  mg_log:
  mg_etc:
